<?php
function get_image_upload_form(){
  $form = '<form method="post" action="" enctype="multipart/form-data">
    <label>Upload file: <input type="file" name="image" accept="image/*" /></label>
    <button type="submit" name="submitted" value="sent">Submit</button>
  </form>';
  return $form;
}
?>
<!DOCTYPE html>
<html>
  <head>
    <title>HTML Form</title>
  </head>
  <body>
    <p>The form is generated by the <code>get_image_upload_form()</code> function.</p>
    <? echo get_image_upload_form() ?>
  </body>
</html>